### ISSUE TITLE
LSP fails to load AsmDude 2.0.0.0

### ISSUE THREAD

**Issue by quantumhog** [SnellerInc/asm-dude#2]
AsmDude2 features are limited to syntax highlighting only.

1. Saving settings resulting with error:
[vs-asmdude-save-error.txt](https://github.com/SnellerInc/asm-dude/files/12587275/vs-asmdude-save-error.txt)

2. Code completions doesn't seem to work.

The only log I found related to AsmDude.
[LSPClient.PlatformLog.xml.txt](https://github.com/SnellerInc/asm-dude/files/12587257/LSPClient.PlatformLog.xml.txt)

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.7.3
Windows 10 Pro 22H2

**Comment by henkjan-sneller** [comment]
The VS extension could either not find the language server provider (LSP), a permissions to read issue, or the LSP crashed due to some missing requirements, hard to tell from here. If there is no `%temp%/VSLogs/AsmDude2/log.svclog` then the LSP never started. 

Could you check if you can run the LSP (make sure to kill it afterwards, its a daemon) On my machine its placed here, yours will differ: `C:\Users\henkj\AppData\Local\Microsoft\VisualStudio\17.0_9b19b0e1Exp\Extensions\Henk-Jan Lebbink\AsmDude2\2.0.0.0\Server\AsmDude2.LSP.exe`) If this runs it will make the above log.

**Comment by henkjan-sneller** [comment]
Here is version 2.0.0.1 [asm-dude2-vsix.vsix.zip](https://github.com/SnellerInc/asm-dude/files/12587970/asm-dude2-vsix.vsix.zip) with some updates that could help.

**Comment by quantumhog** [comment]
Didn't change much but thanks for quick try.

**Comment by HJLebbink** [comment]
> Didn't change much but thanks for quick try.

Was there a popup that the LSP could not be found? Is there a AsmDude2.LSP.exe in the extensions directory? What happens when you run it? Is there briefly a black window (from AsmDude2.LSP.exe)?

**Comment by quantumhog** [comment]
> 
Yes. I see popup window and AsmDude2.LSP.exe in extenstion dir.
Saving settings resulting with the same error and I can't see any additional functionality but syntax highlighting. Should I expect something more?
My cpu (i9-9000K)

**Comment by henkjan-sneller** [comment]
Thanx for all the effort. To be clear. If you see an error message from VS stating that it cannot find/load the LSP, you will only have syntax highlighting; which is nice, but not as important as signature help, code completion, code folding, port usage etc in hovers. 

If you see a terminal (for only a split second) that is from the LSP that runs as a daemon under the VS process, it will hide itself directly after creation. The problem is that this server is not running. And only if I know what causes this I'm confident to add this plugin on the VS extensions portal. All setups I have tried work as expected.

**Comment by quantumhog** [comment]
Let me know if I can help to diagnose the problem on my side. 
You can provide build with some extended log info if you want me to run this on my computer.

**Comment by HJLebbink** [comment]
> Could you check if you can run the LSP (make sure to kill it afterwards, its a daemon) On my machine its placed here, yours will differ: `C:\Users\henkj\AppData\Local\Microsoft\VisualStudio\17.0_9b19b0e1Exp\Extensions\Henk-Jan Lebbink\AsmDude2\2.0.0.0\Server\AsmDude2.LSP.exe`) If this runs it will make the above log.

**Comment by quantumhog** [comment]
Ok. I've tried to run this and it looks like .net 8.0 (preview) is required (so this is the reason). I can install preview version  but maybe 7.0 should be default target.
Framework: 'Microsoft.NETCore.App', version '8.0.0-preview.7.23375.6' (x64)
Should vsix installer take care of all the dependencies?


EDIT:
I did install .Net 8.0-rc1 and I can confirm code completion, instruction popup, code folding is **functional**.

There is console window in the background with bunch of warnings.
`WARNING: parseArch: no arch for str AVX512_VL,AVX512_F
WARNING: parseArch: no arch for str AVX512_VL,AVX512_F
...`

Thank you.
